import { defineConfig } from 'vitepress'

export default defineConfig({
  lang: 'zh-CN',
  title: '机电学院知识库',
  description: '四川农业大学机电学院课程资源共享平台 — 电子/电气/农机/农业工程四专业363门课程',
  head: [
    ['link', { rel: 'icon', href: '/favicon.svg' }],
    ['meta', { name: 'theme-color', content: '#2563eb' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: '机电学院知识库' }],
    ['meta', { property: 'og:description', content: '四川农业大学机电学院课程资源共享平台，电子/电气/农机/农业工程四专业全覆盖' }],
    ['meta', { property: 'og:site_name', content: '机电学院知识库' }],
  ],
  sitemap: { hostname: 'https://scau-knowledge-base-nhlkrpf1.edgeone.cool' },
  themeConfig: {
    logo: '/logo.svg',
    nav: [
      { text: '首页', link: '/' },
      { text: '课程总览', items: [
        { text: '电子科学与技术', link: '/majors/dianzikexue/' },
        { text: '电气工程及自动化', link: '/majors/dianqigongcheng/' },
        { text: '农业机械化', link: '/majors/nongyejixiehua/' },
        { text: '农业工程', link: '/majors/nongyegongcheng/' },
      ]},
      { text: '课程地图', link: '/map' },
      { text: '学长说', link: '/stories' },
      { text: '贡献指南', link: '/contribute' },
      { text: '关于本站', link: '/about' },
    ],
    sidebar: (()=>{let s=(items)=>[{text:'',items}];
    return {
      '/majors/dianzikexue/': s([
        {text:'📖 专业总览',link:'/majors/dianzikexue/'},
        {text:'📘 大一上 13',link:'/majors/dianzikexue/semester1-1'},
        {text:'📗 大一下 9',link:'/majors/dianzikexue/semester1-2'},
        {text:'📙 大二上 13',link:'/majors/dianzikexue/semester2-1'},
        {text:'📙 大二下 15',link:'/majors/dianzikexue/semester2-2'},
        {text:'📕 大三上 18',link:'/majors/dianzikexue/semester3-1'},
        {text:'📕 大三下 19',link:'/majors/dianzikexue/semester3-2'},
        {text:'📔 大四上 3',link:'/majors/dianzikexue/semester4-1'},
        {text:'📔 大四下 3',link:'/majors/dianzikexue/semester4-2'},
      ]),
      '/majors/nongyejixiehua/': s([
        {text:'📖 专业总览',link:'/majors/nongyejixiehua/'},
        {text:'📘 大一上 15',link:'/majors/nongyejixiehua/semester1-1'},
        {text:'📗 大一下 10',link:'/majors/nongyejixiehua/semester1-2'},
        {text:'📙 大二上 13',link:'/majors/nongyejixiehua/semester2-1'},
        {text:'📙 大二下 14',link:'/majors/nongyejixiehua/semester2-2'},
        {text:'📕 大三上 12',link:'/majors/nongyejixiehua/semester3-1'},
        {text:'📕 大三下 9',link:'/majors/nongyejixiehua/semester3-2'},
        {text:'📔 大四上 6',link:'/majors/nongyejixiehua/semester4-1'},
        {text:'📔 大四下 3',link:'/majors/nongyejixiehua/semester4-2'},
      ]),
      '/majors/dianqigongcheng/': s([
        {text:'📖 专业总览',link:'/majors/dianqigongcheng/'},
        {text:'📘 大一上 13',link:'/majors/dianqigongcheng/semester1-1'},
        {text:'📗 大一下 11',link:'/majors/dianqigongcheng/semester1-2'},
        {text:'📙 大二上 12',link:'/majors/dianqigongcheng/semester2-1'},
        {text:'📙 大二下 12',link:'/majors/dianqigongcheng/semester2-2'},
        {text:'📕 大三上 12',link:'/majors/dianqigongcheng/semester3-1'},
        {text:'📕 大三下 12',link:'/majors/dianqigongcheng/semester3-2'},
        {text:'📔 大四上 5',link:'/majors/dianqigongcheng/semester4-1'},
        {text:'📔 大四下 8',link:'/majors/dianqigongcheng/semester4-2'},
      ]),
      '/majors/nongyegongcheng/': s([
        {text:'📖 专业总览',link:'/majors/nongyegongcheng/'},
        {text:'📘 大一上 13',link:'/majors/nongyegongcheng/semester1-1'},
        {text:'📗 大一下 9',link:'/majors/nongyegongcheng/semester1-2'},
        {text:'📙 大二上 16',link:'/majors/nongyegongcheng/semester2-1'},
        {text:'📙 大二下 15',link:'/majors/nongyegongcheng/semester2-2'},
        {text:'📕 大三上 17',link:'/majors/nongyegongcheng/semester3-1'},
        {text:'📕 大三下 8',link:'/majors/nongyegongcheng/semester3-2'},
        {text:'📔 大四上 6',link:'/majors/nongyegongcheng/semester4-1'},
        {text:'📔 大四下 2',link:'/majors/nongyegongcheng/semester4-2'},
      ]),
    };})(),
    search:{provider:'local',options:{translations:{button:{buttonText:'搜索课程'},modal:{displayDetails:'显示详情',noResultsText:'未找到',footer:{selectText:'选择',closeText:'关闭'}}}}},
    footer:{message:'四川农业大学 · 机电学院',copyright:`Copyright © ${new Date().getFullYear()} 机电学院知识库`},
    docFooter:{prev:'上一页',next:'下一页'},outline:{label:'本页目录',level:[2,3]},lastUpdated:false,
  },
  ignoreDeadLinks:true,
})
